FROM nginx

#when we copy the configuration file into our image;
#it will be automatically applied to nginx once a container starts up out of our custom image.
COPY ./default.conf /etc/nginx/conf.d/default.conf